# Base image with OpenJDK 17
FROM openjdk:17

# Expose port 8080 for the application
EXPOSE 8080

# Copy the JAR file from the current directory to the /app directory in the container
COPY build/libs/com.example.ktor-study-all.jar /app/ktor-server.jar

# Set the working directory
WORKDIR /app

# Command to run the application
ENTRYPOINT ["java", "-jar", "ktor-server.jar"]
